### ISSUE TITLE
Trouble with newline

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [max-mapper/json-merge#5]
I am on fedora 24 using nodejs 4.4.6.

When I use json merge on files like the example:

```
{"foo": "bar"}
```

```
{"taco":"pizza"}
```

it works! But when I enter a newline like  this:

```
{
"foo": "bar"}
```

I get this error:

```
undefined:1
{


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at DestroyableTransform.strict (/usr/lib/node_modules/json-merge/node_modules/ldjson-stream/index.js:14:26)
    at DestroyableTransform.transform [as _transform] (/usr/lib/node_modules/json-merge/node_modules/ldjson-stream/node_modules/split2/index.js:27:21)
    at DestroyableTransform.Transform._read (/usr/lib/node_modules/json-merge/node_modules/ldjson-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/lib/node_modules/json-merge/node_modules/ldjson-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/lib/node_modules/json-merge/node_modules/ldjson-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/lib/node_modules/json-merge/node_modules/ldjson-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/lib/node_modules/json-merge/node_modules/ldjson-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at ReadStream.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)
```

**Comment by finnp** [comment]
Hey,

this is because json-merge only works for newline-delimited json [ndjson](http://ndjson.org/). So your JSON is not allowed to have any newlines in it, since it acts as a separator between objects.

Best,
Finn
