### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by trks1970** [max-mapper/json-merge#7]
I have installed json-merge via npm. When I execute it in the same directory where my json files are, using json-merge a.json b.json I get:

`undefined:1
{

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at DestroyableTransform.strict (C:\Users\dev\AppData\Roaming\npm\node_modules\json-merge\node_modules\ldjson-stream\index.js:14:26)
    at DestroyableTransform.transform [as _transform] (C:\Users\dev\AppData\Roaming\npm\node_modules\json-merge\node_modules\split2\index.js:27:21)
    at DestroyableTransform.Transform._read (C:\Users\dev\AppData\Roaming\npm\node_modules\json-merge\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\dev\AppData\Roaming\npm\node_modules\json-merge\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\dev\AppData\Roaming\npm\node_modules\json-merge\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\dev\AppData\Roaming\npm\node_modules\json-merge\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\Users\dev\AppData\Roaming\npm\node_modules\json-merge\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at ReadStream.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)`

**Comment by tonymcnulty** [comment]
This is due to you supplying pretty printed json, which is unsupported here. Pipe your json through json-minify first before performing a merge.
